### ISSUE TITLE
When running /economies set [player] [economy] [amount], the syntax message appears in game, and the enclosed error appears in console.

### ISSUE THREAD

**Issue by snomnomnom** [Daniel-Forge-Development/ForgeEconomies#33]
https://pastebin.com/EjWnSkVr
![ecoerror](https://user-images.githubusercontent.com/74738094/142682167-35881aec-208f-4883-9fc9-d0b26aa9dfbb.PNG)

Have also included my config file, if it is helpful

**Comment by danorris709** [comment]
Are you using pure forge?

**Comment by snomnomnom** [comment]
Mohist. I'm sure thats the issue

**Comment by danorris709** [comment]
That'd be the issue. I assume you've not installed the spigot bridge?
